### ISSUE TITLE
Prohibited terms: master, slave

### ISSUE THREAD

**Issue by cdmauney** [ibm-cloud-docs/RegistryImages#51]
* master: Do not use. Use another term such as "controller", "leader", "manager", "main", "coordinator", "parent", or "primary [server, node, process, or other noun]".
* slave: Do not use. Use another term such as "worker", "child", "helper", "replica", "follower", or "secondary [server, node, process, or other noun]".

https://cloud.ibm.com/docs/RegistryImages?topic=RegistryImages-datashield-mariadb_starter

**Comment by SueGraham** [comment]
@smguilia please can you update this topic - thanks

**Comment by SueGraham** [comment]
@smguilia Just a reminder about this one. Please can you update asap. Thanks

**Comment by smguilia** [comment]
Thanks @SueGraham ... The master /slave terminology is in the code. This change is dependent upon being able to change the code. I have the development team investigating.

**Comment by smguilia** [comment]
@SueGraham Updates made internally. Thanks for your patience while we investigated.

**Comment by SueGraham** [comment]
Updated - all complete
